// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Backend.Entities;

#nullable disable

namespace Backend.DAL
{
    internal partial class CapstoneContext : DbContext
    {
        public CapstoneContext()
        {
        }

        public CapstoneContext(DbContextOptions<CapstoneContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CapstoneClient> CapstoneClients { get; set; }
        public virtual DbSet<CapstoneProject> CapstoneProjects { get; set; }
        public virtual DbSet<DbVersion> DbVersions { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TeamAssignment> TeamAssignments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<CapstoneProject>(entity =>
            {
                entity.HasKey(e => new { e.InstructorId, e.CapstoneClientId })
                    .HasName("PK__Capstone__3FBE41D30DEC2464");

                entity.HasOne(d => d.CapstoneClient)
                    .WithMany(p => p.CapstoneProjects)
                    .HasForeignKey(d => d.CapstoneClientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CapstoneProjects_CapstoneClients");

                entity.HasOne(d => d.Instructor)
                    .WithMany(p => p.CapstoneProjects)
                    .HasForeignKey(d => d.InstructorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CapstoneProjects_Instructors");
            });

            modelBuilder.Entity<TeamAssignment>(entity =>
            {
                entity.HasKey(e => new { e.StudentId, e.ClientId })
                    .HasName("PK_dbo.TeamAssignments");

                entity.HasOne(d => d.Client)
                    .WithMany(p => p.TeamAssignments)
                    .HasForeignKey(d => d.ClientId)
                    .HasConstraintName("FK_dbo.TeamAssignments_dbo.CapstoneClients_ClientId");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.TeamAssignments)
                    .HasForeignKey(d => d.StudentId)
                    .HasConstraintName("FK_dbo.TeamAssignments_dbo.Students_StudentId");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}