// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AppSecurity.Entities
{
    public partial class Instructor
    {
        [Key]
        public int InstructorId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
    }
}