// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend.Entities
{
    internal partial class CapstoneProject
    {
        [Key]
        [Column("CapstoneClientID")]
        public int CapstoneClientId { get; set; }
        [Key]
        [Column("InstructorID")]
        public int InstructorId { get; set; }

        [ForeignKey(nameof(CapstoneClientId))]
        [InverseProperty("CapstoneProjects")]
        public virtual CapstoneClient CapstoneClient { get; set; }
        [ForeignKey(nameof(InstructorId))]
        [InverseProperty("CapstoneProjects")]
        public virtual Instructor Instructor { get; set; }
    }
}